services:
  - type: web
    name: afyarescue-web
    env: docker
    branch: main
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    startCommand: apache2-foreground
    envVars:
      - key: APP_KEY
        value: base64:ZhE1Y3v+VmJNr+0fMGbAeI1UXdUeQCGHh1jj3ismcHM=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://afyarescue-2.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d8s6u1j7uimc73813vu0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: afyarescue_db
      - key: DB_USERNAME
        value: afyarescue_db_user
      - key: DB_PASSWORD
        value: tNqsO7r6OX4P3MhtbMD8m0rlLPvZd8L0
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: MAIL_MAILER
        value: log
      - key: VITE_APP_NAME
        value: AfyaRescue
  - type: worker
    name: afyarescue-queue
    env: docker
    branch: main
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    startCommand: php artisan queue:listen --tries=1 --timeout=120
    envVars:
      - key: APP_KEY
        value: base64:ZhE1Y3v+VmJNr+0fMGbAeI1UXdUeQCGHh1jj3ismcHM=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://afyarescue-2.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d8s6u1j7uimc73813vu0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: afyarescue_db
      - key: DB_USERNAME
        value: afyarescue_db_user
      - key: DB_PASSWORD
        value: tNqsO7r6OX4P3MhtbMD8m0rlLPvZd8L0
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: MAIL_MAILER
        value: log
      - key: VITE_APP_NAME
        value: AfyaRescue